source "http://rubygems.org"

gem 'sinatra'
gem 'sinatra-reloader'
gem 'rack-flash'
gem 'yajl-ruby'
gem 'compass'
gem 'do_mysql'
gem 'dm-mysql-adapter', '~>1.1.0'
gem 'dm-core', '~>1.1.0'
gem 'dm-timestamps', '~>1.1.0'
gem 'dm-validations', '~>1.1.0'
gem 'dm-serializer', '~>1.1.0'
gem 'dm-migrations', '~>1.1.0'
gem 'dm-aggregates', '~>1.1.0'
gem 'dm-pager', '~>1.1.0'
gem 'dm-types', '~>1.1.0'
gem 'slim'
gem 'unicorn'
gem 'rturk'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-openid'
gem 'openid'